<?php
/**
 * Created by PhpStorm.
 * User: johankitelman
 * Date: 27.03.2018
 * Time: 13:02
 */

namespace app\admin;


use app\common\CommonController;
use app\models\General;
use yii\web\HttpException;

class AdminController extends CommonController
{
    public $layout = 'admin';


    public function beforeAction($action)
    {
        if (!General::getSession('admin_auth')) throw new HttpException(404);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}