<?php
/**
 * Created by PhpStorm.
 * User: johankitelman
 * Date: 27.03.2018
 * Time: 12:33
 */

namespace app\common;


use app\models\General;

class AuthedController extends CommonController
{

    public function beforeAction($action)
    {
        if (!General::getSession('auth')) return $this->redirect('/auth');

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}